// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wvbzptucjvhgbkppwxtd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind2YnpwdHVjanZoZ2JrcHB3eHRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyNzIwMDYsImV4cCI6MjA2MTg0ODAwNn0.zIVEgH5j3z3Y_X-rEu7rODGu0H14IYLv3Knil5lY5fM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);