
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uttyuqzdklcjnivmeszo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV0dHl1cXpka2xjam5pdm1lc3pvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1MTA0ODcsImV4cCI6MjA2MjA4NjQ4N30.DdV0z80AK3ybzqgQTDZtHNUW1na61gkJ4RQiAJsWJWQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
